config/routes.rb
Rails.application.routes.draw do
  resources :todos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  # broadcasts_to :itself
  broadcasts_to ->(todo) {['todos']}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.create!(todo_params)
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to @todo }
    end

    # @todo = Todo.new(todo_params)

    # respond_to do |format|
    #   if @todo.save
    #     format.turbo_stream
    #     # format.html { redirect_to todos_path, notice: "Todo was successfully created." }
    #     format.json { render :show, status: :created, location: @todo }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @todo.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/home/index.html.erb
<div class="home">
  <%= link_to '딥 러닝에 의한 주가 예측과 자동 매매', '/tradings', class: 'btn btn-outline-light btn-lg active1 py-4' %>
</div>

app/views/layouts/_flash.html.erb
<div class="flash <%= name %> d-flex flex-row justify-content-between"
	data-controller='flash' data-flash-target='element'>
  <div style="width: 5%"></div>
  <div class='d-flex align-items-center'>
    <span class='text-warning'><%= msg %></span>
  </div>
  <div class='d-flex align-items-center' style="width: 5%">
    <span class='flash_close text-muted' data-action="click->flash#close">
      <i class="fa fa-times-circle"></i>
    </span>    
  </div>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-light fixed-1bottom justify-content-center" id='footer'>
  <span class="navbar-text">
    <small>렉클·Rekcle &copy; 2021</small>
  </span>
</nav>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-expand-xs navbar-dark bg-dark fixed-top' id='header'>
<div class='container'>
    <a class="navbar-brand" href="/">렉클</a>
    <!-- <button class="navbar-toggler navbar-toggler-right" type='button' data-toggle='collapse' data-target='#authentication_menu' aria-controls="authentication_menu" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button> -->

    <!-- <div class="collapse navbar-collapse" id='authentication_menu'>
      <ul class="navbar-nav ml-auto mt-2 align-items-end">
        <li class="nav-item">
          <a href="/tradings" class="nav-link">주가 예측</a>
        </li>
        <li class="nav-item">
          <a href="/tradings/settings" class="nav-link">종목 설정</a>
        </li>
      </ul>
    </div> -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails61CapistranoDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
  	  <main>
        <%= yield %>
      </main>
  	  <%= render 'layouts/footer' %>
      <% flash.each do |name, msg| %>
        <%= render 'layouts/flash', name: name, msg: msg %>
      <% end %>
    </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo, data: { 
  controller: "reset-form", 
  action: "turbo:submit-end->reset-form#reset" }) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%#= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Post', 'data-reset-form-target': 'button', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/todos/_todo.html.erb
<%= turbo_frame_tag todo do %>
  <div class="row mb-3">
    <div class="col-8">
      <%= todo.name %>
    </div>

    <div class="col-4">
      <%= link_to 'Destroy', todo, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
  <hr>
    
<% end %>

app/views/todos/edit.html.erb
<div class='container'>
  <h1>Editing Todo</h1>

  <%= render 'form', todo: @todo %>

  <%= link_to 'Show', @todo %> |
  <%= link_to 'Back', todos_path %>
</div>

app/views/todos/index.html.erb
<div class='container'>
  <h1>Todos</h1>

  <%= turbo_stream_from 'todos' %>

  <%= turbo_frame_tag 'todos' do %>
    <%= render @todos %>
  <% end %>

  <%#= link_to 'New Todo', new_todo_path %>
  <%= turbo_frame_tag 'new_todo', src: new_todo_path, target: '_top' do %>
    <span><%= Time.now %></span>
  <% end %>

</div>

app/views/todos/new.html.erb
<%= turbo_frame_tag 'new_todo' do %>
  <div>
    <h4>New Todo</h4>
    <%= render 'form', { todo: @todo } %>
  </div>
<% end %>

app/views/todos/show.html.erb
<div class='container'>
  <p>
    <strong>Name:</strong>
    <%= @todo.name %>
  </p>

  <%= link_to 'Edit', edit_todo_path(@todo) %> |
  <%= link_to 'Back', todos_path %>
</div>